# Logo
logo_image_source: https://theferryman.gitee.io/img/cat.svg

# Post
default_post_title: Untitled
default_post_author: yangkai

# About Widget
about_widget_nikename: KIM
about_widget_avatar_url: https://theferryman.gitee.io/img/avator.jpg
about_widget_text: "life |  code"
about_widget_bottom: <iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=360 height=86 src="//music.163.com/outchain/player?type=2&id=233974&auto=0&height=66"></iframe>

# Social Media Platforms
social_platforms:
  - url: https://github.com/
    crt_icon: crt-icon-github
  - url: https://twitter.com/ 
    crt_icon: crt-icon-twitter
  - url: https://www.facebook.com/
    crt_icon: crt-icon-google-plus
  - url: https://dribbble.com/
    crt_icon: crt-icon-instagram
  - url: https://github.com/klugjo/hexo-theme-anodyne
    crt_icon: crt-icon-pinterest
# 顶部导航
menu:
#  Home: /
# Archives: /archives
#  Github: https://gitee.com/theferryman
rss: /atom.xml

# footer
footer: Deveye @ All Rights Reserved 2018
# 内容
excerpt_link: 阅读更多
fancybox: true

# 小部件
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

favicon: /favicon.png
